### ISSUE TITLE
carrot only

### ISSUE THREAD

**Issue by dbox** [carrot/roots-mini#47] opened 2016-03-16 01:46 UTC
Is this carrot only for now? Not a problem at all if it is. I was just curious to start seeing how this works. getting this error:

```
➜  roots-mini git:(develop) sprout add roots-mini-base git@github.com:carrot/roots-mini-base.git
✘ Error: Command failed: /bin/sh -c git clone --recursive git@github.com:carrot/roots-mini-base.git /Users/danielbox/.config/sprout/roots-mini-base
Cloning into '/Users/danielbox/.config/sprout/roots-mini-base'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

```

**Comment by kylemac** [comment] 2016-03-16 01:49
@dbox are you able to clone down https://github.com/carrot/roots-mini-base using `git clone` manually? it's a public repo, so you shouldn't be seeing this

**Comment by dbox** [comment] 2016-03-16 01:53
yeah it let me clone that with `git clone https://github.com/carrot/roots-mini-base.git` is that what you meant?

**Comment by kylemac** [comment] 2016-03-16 01:59
yeah, thats what i meant. hmmm try `sprout remove roots-mini-base` and then readding it? i'm not sure why it said permission denied...

**Comment by dbox** [comment] 2016-03-16 02:09
`✘ Error: template roots-mini-base does not exist`

I'm probably doing something dumb-dumb. Thanks for super quick response. I don't want to tie you up giving one-one-one help. I can wait until things are further along.

Excited to see where this goes. Love all you guys are doing :D 

Okay to close unless you think this could be an issue someone else might have.

**Comment by jenius** [comment] 2016-03-16 15:22
I'd love to figure out what's happening here! If you run `sprout ls`, does `roots-mini-base` show up in the list?

**Comment by kylemac** [comment] 2016-03-16 15:29
so, i ran into a similar issue when i just ran the `sprout` test suite locally. it appears to be an issue w/in sprout core. likely due to a dependency update that broke the implementation. this will be a challenge to solve.

**Comment by kylemac** [comment] 2016-03-16 23:56
@dbox this appears to definitely be an issue with the sprout core. i spent some time investigating today, but i lost steam. will try and pick it up again tomorrow

**Comment by dbox** [comment] 2016-03-17 14:21
@jenius this is what I get.:

```
➜  roots-mini git:(develop) sprout ls
- roots-base
```

**Comment by jenius** [comment] 2016-03-17 14:44
@dbox and you ran `sprout add` already? seems like kyle is checking this out now, probably sprout needs a fix or two

**Comment by dbox** [comment] 2016-03-17 14:47
Yep, no worries. Let me know if you want me to test anything else.

**Comment by kylemac** [comment] 2016-03-18 14:47
ok @dbox i've narrowed it down to an issue caused by an update to `bluebird` within `sprout` core. since @jenius  is currently swapping `bluebird` for `when` - we should be close to resolving this particular issue soon. hang tight

**Comment by kylemac** [comment] 2016-03-24 23:14
@dbox a lot of other "stuff" got tied into fixing this issue, but @jenius is close to done. you can follow along https://github.com/carrot/sprout/issues/144

**Comment by dbox** [comment] 2016-03-24 23:16
OH IM WATCHING :+1:

**Comment by kylemac** [comment] 2016-03-24 23:19
i guess its also worth noting that `origin/master` has your fix in it, if you wanted to try before we `npm publish`

**Comment by dbox** [comment] 2016-03-24 23:27
k. i can check in a few

**Comment by dbox** [comment] 2016-03-24 23:43
```
➜  roots-mini git:(develop) npm install sprout-cli -g
/usr/local/bin/sprout -> /usr/local/lib/node_modules/sprout-cli/bin/sprout
/usr/local/lib
└─┬ sprout-cli@0.0.3 
  ├── argparse@1.0.7 
  ├─┬ inquirer@0.8.5
  │ └── figures@1.5.0 
  └─┬ sprout@0.4.4
    └── js-yaml@3.5.5 

➜  roots-mini git:(develop) sprout add roots-mini-base git@github.com:carrot/roots-mini-base.git
✘ Error: Command failed: /bin/sh -c git clone --recursive git@github.com:carrot/roots-mini-base.git /Users/danielbox/.config/sprout/roots-mini-base
Cloning into '/Users/danielbox/.config/sprout/roots-mini-base'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Still getting permission issues. But again, take this all with a grain of salt. I likely don't know what i'm doing...

**Comment by dbox** [comment] 2016-03-24 23:45
waittt... i might have been in develop branch..

**Comment by kylemac** [comment] 2016-03-24 23:47
@dbox try `sprout add roots-mini-base https://github.com/carrot/roots-mini-base.git`  (uses the https clone syntax, rather than ssh)

**Comment by dbox** [comment] 2016-03-24 23:47
I did all this from develop branch btw. master is still showing up as old for me..

**Comment by dbox** [comment] 2016-03-24 23:53
BINGO

```
  roots-mini git:(develop) sprout add roots-mini-base https://github.com/carrot/roots-mini-base.git
✓ template `roots-mini-base` from https://github.com/carrot/roots-mini-base.git added!
➜  roots-mini git:(develop) sprout new roots-mini-base myproject

? What is the name of your project? 
? Describe your project: hello-world
? What is your github username? dbox
✓ template `roots-mini-base` initialized at /Users/danielbox/Sites/dev/roots-mini/myproject!
```
:ok_hand: :ok_hand: :ok_hand:

**Comment by dbox** [comment] 2016-03-24 23:55
https://www.dropbox.com/s/y7debz7xzilsc7i/Screenshot%202016-03-24%2018.55.43.png?dl=0

**Comment by kylemac** [comment] 2016-03-25 00:07
ah, you're using the original `roots` to do that watch. you'll need to use roots-mini. i suggest following the directions i just set up here under `setup` - https://github.com/carrot/roots-mini-test-project

**Comment by kylemac** [comment] 2016-03-25 00:07
@dbox you're so close!

**Comment by kylemac** [comment] 2016-03-25 00:12
you could use that `roots-mini-test-project` too, if you want to avoid the sprout generation next time; although you seemed to have gotten that working :+1:

**Comment by dbox** [comment] 2016-03-25 01:59
![image](https://cloud.githubusercontent.com/assets/296130/14036065/4759d6d8-f203-11e5-9dcc-cce0776f24f4.png)
:+1: :+1:

**Comment by dbox** [comment] 2016-03-25 02:01
have you been able to do any compile time tests for bigger sites?

**Comment by kylemac** [comment] 2016-03-25 02:19
naw, we haven't gotten there yet but a major speed advantage is that after the first compile during a watch, only the files that are changed end up getting recompiled (whereas currently the whole project gets recompiled) so we get major speed boost there for sure. anecdotally, we feel like the initial compile is gonna end up faster as well too though. just haven't benchmarked that yet

**Comment by dbox** [comment] 2016-03-25 02:24
Yeah, definitely.  Exciting stuff.

**Comment by jenius** [comment] 2016-03-30 20:05
:tada: going to close this now, but hit us up whenever if you are experimenting with this! first couple production projects are going to be rolled out on roots mini over the next couple months.

**Closed by jenius** 2016-03-30 20:05 UTC
